dist: xenial

language: node_js

node_js:
  - node

sudo: false

addons:
  - chrome: stable
  
install:
  - npm install web

script:
  - npm ci --prefix=./web/
  - npm run --prefix=./web/ lint
  - npm ci --prefix=./web/
  - npm run --prefix=./web/ test -- --watch=false
  - npm ci --prefix=./web/
  - npm run --prefix=./web/ e2e
