dist: xenial

language: node_js

node_js:
  - 10.12.0

sudo: false

addons:
  - chrome: stable

before install: cd web
install:
  - npm install

script:
  - npm ci
  - npm run lint
  - npm ci
  - npm run test -- --watch=false
  - npm ci 
  - npm run e2e --webdriverUpdate=false
