runtime: nodejs10
 
handlers:
- url: /
  static_files: dist/index.html
  upload: dist/.*

- url: /(.*\.js)
  redirect_http_response_code: 301
  static_files: dist/\1
  upload: dist/.*\.js

- url: /(.*\.scss)
  redirect_http_response_code: 301
  static_files: dist/\1
  mime_type: dist/scss
  upload: dist/.*\.scss

- url: /((?:assets|docs)/.*|favicon\.ico)
  redirect_http_response_code: 301
  static_files: dist/\1
  upload: dist/.*


- url: /.*
  redirect_http_response_code: 301
  static_files: dist/index.html
  upload: dist/.*
