version: 2.1

jobs:
  build:
    docker:
      # We cannot use the new cimg/node images because those don't include
      # any browsers.
      - image: circleci/node:10.21-browsers

    steps:
      - checkout

      - run:
          name: node_modules
          working_directory: web
          command: npm ci

      - run:
          name: lint
          working_directory: web
          command: npm run lint

      - run:
          name: test
          working_directory: web
          command: npm run test -- --watch=false

      - run:
          name: e2e
          working_directory: web
          command: npm run e2e
