name: Deploy to App Engine

on: 
  push:
    branches:
      - main 
  pull_request:

# The golden hash represents the commit of the baseline images that we want to 
# compare our current app against. It is automatically set as the most recent 
# commit to main.
env:
  APPENGINE_VERSION_PREFIX: invalid
  SHA_SHORT: invalid
  CURRENT_HASH: invalid
  GOLDEN_HASH: invalid

jobs:
  appengine-deploy:
    name: Deploy to App Engine
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Set env variables for the push to main
        if: github.ref == 'refs/heads/main'
        run: |
          echo "::set-env name=APPENGINE_VERSION_PREFIX::main"
          echo "::set-env name=SHA_SHORT::$(git rev-parse --short=7 ${{ github.sha }})"
          echo "::set-env name=CURRENT_HASH::${{ github.sha }}"

      - name: Set env variables for the pull request
        if: github.ref != 'refs/heads/main'
        run: |
          echo "::set-env name=APPENGINE_VERSION_PREFIX::pr${{ github.event.pull_request.number }}"
          echo "::set-env name=SHA_SHORT::$(git rev-parse --short=7 ${{ github.event.pull_request.head.sha }})"
          echo "::set-env name=CURRENT_HASH::${{ github.event.pull_request.head.sha }}"
      
      - name: Set golden hash
        run: |
          echo "::set-env name=GOLDEN_HASH::$(git ls-remote git://github.com/googleinterns/step189-2020.git refs/heads/main | cut -f 1)"
          
      - name: Build
        working-directory: web
        run: |
          npm ci
          npm run genproto
          npm run build

      # Use Google Cloud credentials to deploy an App Engine Application:
      # https://github.com/GoogleCloudPlatform/github-actions/tree/master/appengine-deploy
      - id: deploy
        name: Deploy to App Engine
        uses: GoogleCloudPlatform/github-actions/appengine-deploy@master
        with: 
          credentials: ${{ secrets.APPENGINE_SA_KEY_B64 }}
          project_id: ${{ secrets.PROJECT_ID }}
          deliverables: ${{ github.workspace }}/web/app.yaml
          version: ${{ env.APPENGINE_VERSION_PREFIX }}-${{ env.SHA_SHORT }}
          promote: false
      
      - id: test
        name: Test the deloyed URL
        run: curl --fail "${{ steps.deploy.outputs.url }}"
        
      - name: Test screenshots using Happo
        working-directory: web
        run: npm run happo-ci-github-actions
        env:
          PREVIOUS_SHA: ${{ env.GOLDEN_HASH }}
          CURRENT_SHA: ${{ env.CURRENT_HASH }}
          CHANGE_URL: https://github.com/googleinterns/step189-2020/commit/${{ env.CURRENT_HASH }}
          HAPPO_API_KEY: ${{ secrets.HAPPO_API_KEY }}
          HAPPO_API_SECRET: ${{ secrets.HAPPO_API_TOKEN }}
          URL: https://${{ env.APPENGINE_VERSION_PREFIX }}-${{ env.SHA_SHORT }}-dot-step189-2020.uc.r.appspot.com/

