name: App Engine Deploy Integration

on: 
  push:
    branches:
      - main 
  pull_request:

env:
  APPENGINE_VERSION: invalid

jobs:
  appengine-deploy:
    name: App Engine Deploy Integration
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - id: vars
        name: Declare sha_short as a variable
        shell: bash
        run: echo "::set-output name=sha_short::$(git rev-parse --short=7 ${{ github.sha }})"

      - name: Set APPENGINE_VERSION to main
        if: github.ref == 'refs/heads/main'
        run: echo '::set-env name=APPENGINE_VERSION::main'

      - name: Set APPENGINE_VERSION to current PR
        if: github.ref != 'refs/heads/main'
        run: echo '::set-env name=APPENGINE_VERSION::pr${{ github.event.pull_request.number }}'

        # Use Google Cloud credentails to deploy an App Engine Application:
        # https://github.com/GoogleCloudPlatform/github-actions/tree/master/appengine-deploy
      - id: deploy
        name: Deploy to App Engine for the current PR
        uses: GoogleCloudPlatform/github-actions/appengine-deploy@master
        with: 
          credentials: ${{ secrets.APPENGINE_SA_KEY_B64 }}
          project_id: ${{ secrets.PROJECT_ID }}
          deliverables: ${{ github.workspace }}/app.yaml
          version: ${{ env.APPENGINE_VERSION }}-${{ steps.vars.outputs.sha_short}}
          promote: false
      
      - id: test
        name: Test the deloyed URL
        run: curl "${{ steps.deploy.outputs.url }}"
