name: Build Angular on GitHub Actions

on:
  push:
    branches: 
      - github-actions

jobs:
  build:
    name: Lint, Test, E2E
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Check out
        uses: actions/checkout@v1

      - name: Use Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version:
            ${{ matrix.node-version }}

      - name: Lint
        working-directory: web
        run: |
          npm ci
          npm run lint
          
      - name: Test
        working-directory: web
        run: |
          npm ci
          npm run test -- --watch=false
      
      - name: E2E
        working-directory: web
        run: |
          npm ci
          npm run e2e
